# Generated by Django 3.1.1 on 2020-09-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stduent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30, unique=True)),
                ('spwd', models.CharField(max_length=20)),
            ],
        ),
    ]
